import { cVar } from "@src/helpers";
import { COLORS, FONT_FAMILY } from "@src/theme/constants";
import type { NextPage } from "next";
import Head from "next/head";
import styled from "styled-components";

const Text = styled.h1`
  color: green;
  font-family: ${cVar("dinAlternate")};
`;

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>JoshFolio | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Text>JOSHUA OLAJIDE FE</Text>
    </div>
  );
};

export default Home;
