import React from "react";
import Hero from "@src/components/Hero/Hero";
import { cVar } from "@src/helpers";
import type { NextPage } from "next";
import Head from "next/head";
import styled from "styled-components";
import gsap from "gsap";
import Defaultlayout from "@src/layout/DefaultLayout";

const Text = styled.h1`
  color: ${cVar("white")};
  font-family: ${cVar("dinAlternate")};
`;

const Container = styled.div`
  width: 100%;
  height: 2000px;
  background-color: ${cVar("black2")};
`;

const Home: NextPage = () => {
  const timeline = gsap.timeline();

  return (
    <Defaultlayout>
      <Container>
        <Head>
          <title>JoshFolio | Home</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Hero timeline={timeline} />

        <Text>JOSHUA OLAJIDE FE</Text>
        <Text>JOSHUA OLAJIDE FE</Text>
        <Text>JOSHUA OLAJIDE FE</Text>
      </Container>
    </Defaultlayout>
  );
};

export default Home;
