import { cVar } from "@src/helpers";
import type { NextPage } from "next";
import Head from "next/head";
import { useEffect } from "react";
import styled from "styled-components";

const Text = styled.h1`
  color: darkgreen;
  font-family: ${cVar("dinAlternate")};
`;

const Container = styled.div`
  width: 100%;
  height: 2000px;
  background-color: gray;
`;

export const Cursor = styled.div`
  position: fixed;
  height: 8px;
  width: 8px;
  border-radius: 50%;
  transform: translateX(-50%) translateY(-50%);
  mix-blend-mode: difference !important;
  pointer-events: none;

  &::nth-child(1) {
    background: ${cVar("white")};
  }
  &::nth-child(2) {
    background-color: #fefefe;
    width: 22px;
    height: 22px;
    transition: width 400ms ease, height 400ms ease;
  }
`;

const Home: NextPage = () => {
  // document.querySelector("document")
  useEffect(() => {
    if (typeof window !== undefined) {
      console.log("Document", document);
    }
  }, []);
  return (
    <Container>
      <Cursor></Cursor>
      <Head>
        <title>JoshFolio | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Text>JOSHUA OLAJIDE FE</Text>
      <Text>JOSHUA OLAJIDE FE</Text>
      <Text>JOSHUA OLAJIDE FE</Text>
      <Text>JOSHUA OLAJIDE FE</Text>
      <Text>JOSHUA OLAJIDE FE</Text>
      <Text>JOSHUA OLAJIDE FE</Text>
      <Text>JOSHUA OLAJIDE FE</Text>
      <Text>JOSHUA OLAJIDE FE</Text>
      <Text>JOSHUA OLAJIDE FE</Text>
      <Text>JOSHUA OLAJIDE FE</Text>
      <Text>JOSHUA OLAJIDE FE</Text>
      <Text>JOSHUA OLAJIDE FE</Text>
      <Text>JOSHUA OLAJIDE FE</Text>
      <Text>JOSHUA OLAJIDE FE</Text>
      <Text>JOSHUA OLAJIDE FE</Text>
      <Text>JOSHUA OLAJIDE FE</Text>
      <Text>JOSHUA OLAJIDE FE</Text>
      <Text>JOSHUA OLAJIDE FE</Text>
      <Text>JOSHUA OLAJIDE FE</Text>
      <Text>JOSHUA OLAJIDE FE</Text>
      <Text>JOSHUA OLAJIDE FE</Text>
      <Text>JOSHUA OLAJIDE FE</Text>
      <Text>JOSHUA OLAJIDE FE</Text>
      <Text>JOSHUA OLAJIDE FE</Text>
      <Text>JOSHUA OLAJIDE FE</Text>
      <Text>JOSHUA OLAJIDE FE</Text>
      <Text>JOSHUA OLAJIDE FE</Text>
      <Text>JOSHUA OLAJIDE FE</Text>
      <Text>JOSHUA OLAJIDE FE</Text>
      <Text>JOSHUA OLAJIDE FE</Text>
      <Text>JOSHUA OLAJIDE FE</Text>
      <Text>JOSHUA OLAJIDE FE</Text>
      <Text>JOSHUA OLAJIDE FE</Text>
      <Text>JOSHUA OLAJIDE FE</Text>
      <Text>JOSHUA OLAJIDE FE</Text>
      <Text>JOSHUA OLAJIDE FE</Text>
      <Text>JOSHUA OLAJIDE FE</Text>
      <Text>JOSHUA OLAJIDE FE</Text>
      <Text>JOSHUA OLAJIDE FE</Text>
      <Text>JOSHUA OLAJIDE FE</Text>
      <Text>JOSHUA OLAJIDE FE</Text>
      <Text>JOSHUA OLAJIDE FE</Text>
      <Text>JOSHUA OLAJIDE FE</Text>
    </Container>
  );
};

export default Home;
